//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum DeviceTypeID {
  YDLIDAR_TYPE_SERIAL = 0x0,
  YDLIDAR_TYPE_TCP = 0x1,
  YDLIDAR_TYPC_UDP = 0x2
}
