//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum DriverError {
  NoError = 0,
  DeviceNotFoundError,
  PermissionError,
  UnsupportedOperationError,
  UnknownError,
  TimeoutError,
  NotOpenError,
  BlockError,
  NotBufferError,
  TrembleError,
  LaserFailureError
}
