//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LaserFan : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LaserFan(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LaserFan obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LaserFan() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ydlidarPINVOKE.delete_LaserFan(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ulong stamp {
    set {
      ydlidarPINVOKE.LaserFan_stamp_set(swigCPtr, value);
    } 
    get {
      ulong ret = ydlidarPINVOKE.LaserFan_stamp_get(swigCPtr);
      return ret;
    } 
  }

  public uint npoints {
    set {
      ydlidarPINVOKE.LaserFan_npoints_set(swigCPtr, value);
    } 
    get {
      uint ret = ydlidarPINVOKE.LaserFan_npoints_get(swigCPtr);
      return ret;
    } 
  }

  public LaserPoint points {
    set {
      ydlidarPINVOKE.LaserFan_points_set(swigCPtr, LaserPoint.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ydlidarPINVOKE.LaserFan_points_get(swigCPtr);
      LaserPoint ret = (cPtr == global::System.IntPtr.Zero) ? null : new LaserPoint(cPtr, false);
      return ret;
    } 
  }

  public LaserConfig config {
    set {
      ydlidarPINVOKE.LaserFan_config_set(swigCPtr, LaserConfig.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ydlidarPINVOKE.LaserFan_config_get(swigCPtr);
      LaserConfig ret = (cPtr == global::System.IntPtr.Zero) ? null : new LaserConfig(cPtr, false);
      return ret;
    } 
  }

  public LaserFan() : this(ydlidarPINVOKE.new_LaserFan(), true) {
  }

}
