//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum LidarTypeID {
  TYPE_TOF = 0,
  TYPE_TRIANGLE = 1,
  TYPE_TOF_NET = 2,
  TYPE_Tail
}


//TYPE_TOF TG TX LiDAR.
//TYPE_TRIANGLE G4.G6.G2 LiDAR.
//TYPE_TOF_NET T15 LiDAR.
//TYPE_Tail