//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum LidarProperty {
  LidarPropSerialPort = 0, 
  LidarPropIgnoreArray, 
  LidarPropSerialBaudrate = 10,
  LidarPropLidarType, // 11
  LidarPropDeviceType, //12
  LidarPropSampleRate, //13
  LidarPropAbnormalCheckCount, //14 abnormal maximum check times
  LidarPropMaxRange = 20,
  LidarPropMinRange, //21
  LidarPropMaxAngle, //22
  LidarPropMinAngle, //23
  LidarPropScanFrequency, //24
  LidarPropFixedResolution = 30,
  LidarPropReversion, //31 lidar reversion flag
  LidarPropInverted, //32 lidar inverted flag
  LidarPropAutoReconnect, //33 ,lidar hot plug flag
  LidarPropSingleChannel, //34
  LidarPropIntenstiy, //35 , 
  LidarPropSupportMotorDtrCtrl, //36 , lidar support motor Dtr ctrl flag
  LidarPropSupportHeartBeat //37
}


//LidarPropSerialPort Lidar serial port or network ipaddress
//LidarPropIgnoreArray Lidar ignore angle array
//LidarPropSerialBaudrate lidar serial baudrate or network port
//LidarPropLidarType lidar type code
//LidarPropDeviceType lidar connection type code
//LidarPropSampleRate lidar sample rate
//LidarPropAbnormalCheckCount abnormal maximum check times
//LidarPropMaxRange lidar maximum range
//LidarPropMinRange lidar minimum range
//LidarPropMaxAngle lidar maximum angle
//LidarPropMinAngle lidar minimum angle
//LidarPropScanFrequency lidar scanning frequency
//LidarPropFixedResolution fixed angle resolution flag
//LidarPropReversion lidar reversion flag
//LidarPropInverted lidar inverted flag
//LidarPropAutoReconnect lidar hot plug flag
//LidarPropSingleChannel lidar single - channel flag
//LidarPropIntenstiy lidar intensity flag
//LidarPropSupportMotorDtrCtrl lidar support motor Dtr ctrl flag