//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LidarVersion : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LidarVersion(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LidarVersion obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LidarVersion() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ydlidarPINVOKE.delete_LidarVersion(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public byte hardware {
    set {
      ydlidarPINVOKE.LidarVersion_hardware_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LidarVersion_hardware_get(swigCPtr);
      return ret;
    } 
  }

  public byte soft_major {
    set {
      ydlidarPINVOKE.LidarVersion_soft_major_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LidarVersion_soft_major_get(swigCPtr);
      return ret;
    } 
  }

  public byte soft_minor {
    set {
      ydlidarPINVOKE.LidarVersion_soft_minor_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LidarVersion_soft_minor_get(swigCPtr);
      return ret;
    } 
  }

  public byte soft_patch {
    set {
      ydlidarPINVOKE.LidarVersion_soft_patch_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LidarVersion_soft_patch_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_char sn {
    set {
      ydlidarPINVOKE.LidarVersion_sn_set(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ydlidarPINVOKE.LidarVersion_sn_get(swigCPtr);
      SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
      return ret;
    } 
  }

  public LidarVersion() : this(ydlidarPINVOKE.new_LidarVersion(), true) {
  }

}
