//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ydlidar {
  public static void os_init() {
    ydlidarPINVOKE.os_init();
  }

  public static bool os_isOk() {
    bool ret = ydlidarPINVOKE.os_isOk();
    return ret;
  }

  public static void os_shutdown() {
    ydlidarPINVOKE.os_shutdown();
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t lidarPortList() {
    SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t ret = new SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t(ydlidarPINVOKE.lidarPortList(), true);
    return ret;
  }

	//initialize LaserFan

	public static void LaserFanInit(LaserFan to_init) {
    ydlidarPINVOKE.LaserFanInit(LaserFan.getCPtr(to_init));
  }

  public static void LaserFanDestroy(LaserFan to_destroy) {
    ydlidarPINVOKE.LaserFanDestroy(LaserFan.getCPtr(to_destroy));
  }

}
